# To be used with docker-compose -f docker-compose.yml -f docker-compose.dev.yml [build|up|down|etc]

services:
  ia:
    command: ["fastapi", "dev", "adumbra/ia", "--reload", "--host", "0.0.0.0", "--port", "6001"]
    volumes:
      - ${PWD}/backend/adumbra:/workspace/adumbra
  webserver:
    environment:
      # https://flask-fr.readthedocs.io/server/#command-line
      - FLASK_APP=webserver
      - FLASK_ENV=development
      # https://flask.palletsprojects.com/en/stable/config/#DEBUG
      - FLASK_DEBUG=true
  frontend:
    build:
      target: develop
    volumes:
      # Enable hot reloading for frontend development
      - "${PWD}/client:/workspace/client"
      # But don't let locally installed node modules interfere with the container
      # (credit: https://stackoverflow.com/a/37898591)
      - "/workspace/client/node_modules/"
      # Override named mounts to track added models/data
      - "${PWD}/datasets:/datasets"
      - "${PWD}/models:/models"
