include:
  - ${PWD}/compose-extensions/networks-volumes.yml

services:
  ia:
    extends:
      file: ${PWD}/compose-extensions/compose-base-service.yml
      service: service-common
    image: ia_cpu
    build:
      dockerfile: ${PWD}/Dockerfile.backend
      target: adumbra-ia
    ports:
      - 6000:6000
    environment:
      - FILE_WATCHER=true
      - FLASK__SECRET_KEY=RandomSecretKeyHere
      - FLASK_APP=ia
      # Install IA aplications or not
      - IA__SAM2__DEFAULT_MODEL_PATH=/models/sam2.1_hiera_base_plus.pt
      - IA__SAM2__DEFAULT_MODEL_CONFIG=configs/sam2.1/sam2.1_hiera_b+.yaml
      - IA__ZIM__DEFAULT_MODEL_PATH=/models/zim/
      - IA__ZIM__DEFAULT_MODEL_TYPE=vit_b
