include:
  - ${PWD}/compose-extensions/networks-volumes.yml

services:
  ia:
    extends:
      file: ${PWD}/compose-extensions/compose-base-service.yml
      service: service-common
    image: ia_cpu
    build:
      dockerfile: ${PWD}/Dockerfile.backend
      target: adumbra-ia
    ports:
      - 6001:6001
    environment:
      - FILE_WATCHER=true
      - FLASK__SECRET_KEY=RandomSecretKeyHere
      - FLASK_APP=ia
      # Configure IA models with default weights and configs, assuming the user ran
      # models/zim.sh etc and kept the path names the same
      - IA__SAM2__CKPT_PATH=/models/sam2.1_hiera_base_plus.pt
      - IA__SAM2__CONFIG_FILE=configs/sam2.1/sam2.1_hiera_b+.yaml
      - IA__ZIM__CHECKPOINT=/models/zim/
