networks:
  adumbra_network:
    external: false

services:
  ia:
    extends:
      file: ./ia-cpu.yml
      service: ia
    image: ia_gpu
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ["0"]
                capabilities: ["gpu"]
    environment:
      - DEVICE=cuda
