repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--ignore-patterns=venv, --rcfile=backend/pyproject.toml]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check-only]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--check, --config=backend/pyproject.toml]
      - id: unimport
        name: unimport
        entry: unimport
        language: system
        types: [python]
        args: [--diff, --config=backend/pyproject.toml]
