name: Formatting check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled

jobs:
  black-pylint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements-dev-pinned.txt

      - name: Install project dependencies
        working-directory: backend
        run: pip install -r requirements-dev-pinned.txt --no-deps

      - name: Run Unimport
        working-directory: backend
        run: |
          unimport --diff

      - name: Run Black
        working-directory: backend
        run: |
          black --check .

      - name: Run isort
        working-directory: backend
        run: |
          isort --check-only .

      - name: Run Pylint (source files)
        if: always()
        run: pylint --rcfile ./backend/pyproject.toml backend/adumbra/ia
